using Microsoft.EntityFrameworkCore;

public class ShoppingCartDbContext : DbContext  // DbContext name changed for clarity
{
    public ShoppingCartDbContext(DbContextOptions<ShoppingCartDbContext> options) : base(options)
    {
    }

    public DbSet<CartItem> CartItems { get; set; } // Single DbSet for CartItem

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Configure relationships are not needed for a single table

        // Configure indexes

        // Create a unique index on the Name column (assuming it identifies the product)
        modelBuilder.Entity<CartItem>()
          .HasIndex(ci => ci.Name)
          .IsUnique();
    }
}

public class CartItem
{
    public int Id { get; set; } // Unique identifier (autogenerated)
    public string? Name { get; set; }
    public decimal Price { get; set; }
}
